### ISSUE TITLE
snoptmex - undefined function issue

### ISSUE THREAD

**Issue by HyeokjoonKwon** [snopt/snopt-matlab#10]
I'm trying to use SNOPT in Matlab, and found a problem that 'snoptmex' is undefined in Matlab. Although 'snoptmex' is used in several functions such as 'snscreen', there is no snoptmex.m(but only is snoptmex.f90) I think this is why Matlab can't treat 'snoptmex' as a defined function.
How can I resolve this problem?
Thank you for reading.

**Comment by gnowzil** [comment]
snoptmex is the name of the Matlab executable file.  It should have the file extension: *.mex(maci64/a64/w64/w32) for macos/linux/windows 64/windows 32.  It is not an m-file.

Do you have that file?  If not, you can request a trial copy from https://ccom.ucsd.edu/~optimizers/downloads/

**Comment by HyeokjoonKwon** [comment]
Actually, I'd requested a trial copy before, but I haven't get it yet. I'm going to request again through that link.
Thank you for the help.

**Comment by gnowzil** [comment]
I just replied to your request right now.  Your earlier request was approved on Oct 4 -- maybe it went into spam or something.  If you don't get the email in the next few hours, let me know.

**Comment by gnowzil** [comment]
I just looked more closely -- your first email address was entered incorrectly (ia vs ai).  Let me know if you have any more questions.

**Comment by HyeokjoonKwon** [comment]
I really appreciate it.
