### ISSUE TITLE
'Invalid MEX-file' error

### ISSUE THREAD

**Issue by ytiang** [snopt/snopt-matlab#12]
I'm using precompiled Matlab Libraries, an error occurred when I ran test example:
````
Invalid MEX-file '/home/yangt/workspace/matlabProjects/snopt-matlab-2.5.0/matlab/snoptmex.mexa64':
libgfortran.so.4: cannot open shared object file: No such file or directory.
Error in snscreen (line 18)
  snoptmex( screenon );
Error in runNPexamples (line 6)
snscreen on 
````
My system is Ubuntu 16.04 and MATLAB version is 2016a. Could you give me some advise how to solve this problem? Thanks for your reading.

**Comment by gnowzil** [comment]
You're missing the `gfortran` library. Install `gfortran` (`sudo apt-get install gfortran`) and it should solve the problem.

**Comment by ytiang** [comment]
thanks for your hint, problem has been solved!
