### ISSUE TITLE
Unrecognized function or variable 'sqoptmex'

### ISSUE THREAD

**Issue by guzhaoyuan** [snopt/snopt-matlab#13]
I got the snoptmex.mexa64 and used it in Matlab R2019b.

I could run `runNPexamples`, the program could solve and get results.

But when I run `runQPexamples`, the program fail with the following error.
```
Unrecognized function or variable 'sqoptmex'.
Error in sqscreen (line 18)
  sqoptmex( screenon );
Error in runQPexamples (line 6)
sqscreen on 
```

**Comment by gnowzil** [comment]
Do you have the sqopt mexfile and is it in a directory on your path?

**Comment by guzhaoyuan** [comment]
I don't have sqopt. I thought it was included in the snopt mexfile. Do I need to file a separate request for sqopt?

**Comment by gnowzil** [comment]
You can pass QPs through SNOPT, which should detect it and call SQOPT.  However, if you want to explicitly use SQOPT through matlab, you'll need to get sqoptmex as well.

(I've updated your download request so if you go back to our downloads page, you should see SQOPT).

**Comment by guzhaoyuan** [comment]
Thanks, I saw the SQOPT now. But when I click on the download button, it tells me that license key not found.
![Capture](https://user-images.githubusercontent.com/11495993/70939268-e238d980-2015-11ea-8a9d-2d9ea6376b60.PNG)

**Comment by gnowzil** [comment]
should be fixed now.  sorry about that!

**Comment by guzhaoyuan** [comment]
Thank you it works now.
