### ISSUE TITLE
reading snspec through snsolve interface not working in v3.0

### ISSUE THREAD

**Issue by sh-cau** [snopt/snopt-matlab#15]
When calling 
`info = snspec(specsfile)`
in _snsolve_, the command line outputs that my specsfile was successfully read but the `info` variable is 0 when it should be either 101 or 107 and subsequently `end_snopt()` is called. I hotfixed this issue with
`if info == 0`
    `    info = 101;`
`end`

**Comment by gnowzil** [comment]
Updated mex-files shouldn't be doing this.  What version of SNOPT does it say at the top of a run?

**Comment by s1monhell** [comment]
Sorry, I am using snopt v7.6.

**Comment by gnowzil** [comment]
You might want to get an updated mex-file.  It should fix this bug :-)

https://ccom.ucsd.edu/~optimizers/downloads/
