### ISSUE TITLE
Invalid MEX-file' error

### ISSUE THREAD

**Issue by yuecaihong123** [snopt/snopt-matlab#17]
I'm using precompiled Matlab Libraries, an error occurred when I ran test example:

t1diet: Solving diet LP problem using SNOPT ... error snoptcmex
Invalid SNOPT Mex File
error snprint (line 28)
  snoptcmex( openprintfile, filename );
erro snopt (line 255)
snprint(printfile);
error  t1diet (line 10)
[x,F,INFO,xmul,Fmul,xstate,Fstate,output]= snopt( x, xlow, xupp, xmul, xstate, ...
error runNPexamples (line 8)
t1diet; 

my system is windows,my matlab is R2016a,could you please give me some advice,thanks very much.

**Comment by gnowzil** [comment]
We haven't provided or supported snoptcmex files in almost 10 years.  I'd recommend you update to using the current version, which you can get a trial of at https://ccom.ucsd.edu/~optimizers/
