### ISSUE TITLE
precompiled-snoptmex.mexw64

### ISSUE THREAD

**Issue by salimoha** [snopt/snopt-matlab#8]
after running ./configure and make install a set of **precompiled-**snoptmex.mex* gets generate however in order to snopt matlab code work, they need to be modified as snoptmex.mex*.

**Comment by gnowzil** [comment]
precompiled-snoptmex.* files are included in the SNOPT package, built at the time the package is put together for release.  They are not created from the configure or make install process.  configure/make creates fresh files named snoptmex.mex*,

**Comment by gnowzil** [comment]
If you want to use the included precompiled files, then you do have to rename them (see https://ccom.ucsd.edu/~optimizers/usage/matlab/) but you don't need to configure/make beforehand -- they are ready for use immediately.
